name: sonar-scan

on:
  push:
    branches:
      - main

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
              SONAR_TOKEN: ${{ secrets.SONAR }}
        with:
          args: >
              -Dsonar.organization=tanveerkkhan89
              -Dsonar.projectKey=my-springboot-app

     