name: sonar-scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
        with:
          args: >
              -Dsonar.organization=tanveerkkhan89
              -Dsonar.projectKey=my-springboot-app  

     