name: sonar-scan

on:
  push:
    branches:
      - main

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        env:
              SONAR_TOKEN: ${{ secrets.SONAR }}
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
              -Dsonar.organization="tanveerkkhan89"
              -Dsonar.projectKey="my-springboot-app"

     