name: sonar-scan

on:
  push:
    branches:
      - main

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Analyze with Maven
        run: mvn clean verify sonar:sonar -Dsonar.login=${{ secrets.SONAR }}

      - name: Upload code coverage to SonarCloud
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          args: >
            -Dsonar.organization=tanveerkkhan89
            -Dsonar.projectKey=my-springboot-app
            -Dsonar.branch.name=${{ github.ref_name }}
            -Dsonar.login=${{ secrets.SONAR }}
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     